import Head from "next/head";
import Hero from "../components/Hero";
import Instagram from "../components/Instagram";
import Testimonals from "../components/Testimonals";
import  FeaturedPosts  from '../sections/FeaturedPosts';


export default function Home() {


  return (
    <>
      <Head>
        <title>STU TALK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <MagicWand /> */}
      <Hero
        heading="STUTALKS"
        message="I capture moments in nature and keep them alive."
      />
      <Testimonals />
      <FeaturedPosts />
      <Instagram />
    </>
  );
}


